name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn version check
        name: Version Check
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: yarn install
        name: Install Dependencies
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: yarn ci
        name: Execute Tests
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish coverage to codecov.io
        uses: codecov/codecov-action@v1.0.3
        if: success() && matrix.node-version == '14.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  auto-merge:
    name: Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot-preview[bot]'
    needs:
      - build
    steps:
      - name: auto-merge
        if: github.actor == 'dependabot-preview[bot]'
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_PAT }}
